# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Common constants to be used for parser tool."""


KEY_AUTHOR = 'author'
KEY_AVG_PARSE_DURATION = 'avgParseDuration'
KEY_CATEGORY = 'category'
KEY_CBN = 'cbn'
KEY_CBN_PARSER = 'cbnParsers'
KEY_CBN_SNIPPET = 'cbnSnippet'
KEY_CHANGELOGS = 'changelogs'
KEY_CONFIG = 'config'
KEY_CONFIG_ID = 'configId'
KEY_CREATE_TIME = 'createTime'
KEY_CREATOR = 'creator'
KEY_CUSTOMER = 'customer'
KEY_DATA = 'data'
KEY_DROP_TAG_COUNTS = 'dropTagCounts'
KEY_END_TIME = 'end_time'
KEY_ENTRIES = 'entries'
KEY_ERROR = 'error'
KEY_ERROR_ID = 'errorId'
KEY_ERROR_MESSAGE = 'errorMsg'
KEY_ERROR_MSG = 'errorMsg'
KEY_ERROR_TIME = 'errorTime'
KEY_ERRORS = 'errors'
KEY_EVENT_CATEGORY_COUNTS = 'eventCategoryCounts'
KEY_EVENT_COUNT = 'eventCount'
KEY_EXTENSION_VALIDATION_REPORT = 'extensionValidationReport'
KEY_FAILED_LOG_COUNT = 'failedLogCount'
KEY_FIELD_EXTRACTORS = 'fieldExtractors'
KEY_GENERIC_EVENT_COUNT = 'genericEventCount'
KEY_GENERIC_EVENT_PERCENTAGE = 'genericEventPercentage'
KEY_INPUT_CBN_SNIPPET = 'cbn_snippet'
KEY_INSTANCE = 'instance'
KEY_INSTANCES = 'instances'
KEY_INVALID_CONFIG_ERROR = 'invalidConfigError'
KEY_INVALID_LOG_COUNT = 'invalidLogCount'
KEY_LAST_LIVE_TIME = 'lastLiveTime'
KEY_LOCATION = 'location'
KEY_LOCATIONS = 'locations'
KEY_LOG = 'log'
KEY_LOG_DATA = 'logData'
KEY_LOG_ENTRY = 'logEntry'
KEY_LOG_ENTRY_COUNT = 'logEntryCount'
KEY_LOG_TYPE = 'log_type'
KEY_LOGS = 'logs'
KEY_LOGTYPE = 'logType'
KEY_LOGTYPES = 'logTypes'
KEY_LOW_CODE = 'lowCode'
KEY_MAX_ENTRIES = 'max_entries'
KEY_MAX_PARSE_DURATION = 'maxParseDuration'
KEY_MESSAGE = 'message'
KEY_NAME = 'name'
KEY_NORMALIZATION_PERCENTAGE = 'normalizationPercentage'
KEY_ON_ERROR_COUNT = 'onErrorCount'
KEY_PARSED_EVENTS = 'parsedEvents'
KEY_PARSER = 'parser'
KEY_PARSER_EXTENSION = 'parserExtension'
KEY_PARSER_EXTENSION_ID = 'parserExtensionID'
KEY_PARSER_EXTENSIONS = 'parserExtensions'
KEY_PARSER_ID = 'parserID'
KEY_PARSERS = 'parsers'
KEY_PARSING_ERRORS = 'parsingErrors'
KEY_PARSING_ERRORS = 'parsingErrors'
KEY_PARSING_ERRORS = 'parsingErrors'
KEY_PREDICTIONS = 'predictions'
KEY_PROJECT = 'project'
KEY_PROJECTS = 'projects'
KEY_RELEASE_STAGE = 'releaseStage'
KEY_RESULT = 'result'
KEY_RUN_PARSER_RESULTS = 'runParserResults'
KEY_SHA256 = 'sha256'
KEY_SKIP_VALIDATION_ON_NO_LOGS = 'skipValidationOnNoLogs'
KEY_SCORE = 'score'
KEY_SOURCE = 'source'
KEY_START_TIME = 'start_time'
KEY_STATE = 'state'
KEY_STATE_LAST_CHANGED_TIME = 'stateLastChangedTime'
KEY_STATEDUMP_ALLOWED = 'statedump_allowed'
KEY_STATEDUMP_RESULT = 'statedumpResult'
KEY_STATEDUMP_RESULTS = 'statedumpResults'
KEY_STATS = 'stats'
KEY_SUBMIT_TIME = 'submitTime'
KEY_SUCCESSFULLY_NORMALIZED_LOG_COUNT = 'successfullyNormalizedLogCount'
KEY_TYPE = 'type'
KEY_VALIDATION_ERRORS = 'validationErrors'
KEY_VALIDATED_ON_EMPTY_LOGS = 'validatedOnEmptyLogs'
KEY_VALIDATION_REPORT = 'validationReport'
KEY_VALIDATION_REPORT_ID = 'validationReportID'
KEY_VALIDATION_REPORTS = 'validationReports'
KEY_VALIDATION_STAGE = 'validationStage'
KEY_VERDICT = 'verdict'
